const initialState = {
  lat: 0,
  lng: 0,
  authenticated: false,
  displayLoginButton: true,
  authMessage: null,
  message: null,
  destination: null,
  days: null,
  trip: null,
  gotActivities: null,
  gotHotels: null,
  gotRestaurants: null,
  finalizeMessage: null,
  activities: null,
  hotels: null,
  activityType: null,
  progression: -1,
  selectedCard: null,
  trips: null,
  restaurants: null,
  currentUser: null,
  currentRoute: "landing",
  logout: false
};
export default initialState;
